networks:
  pg-net:
    external: true  # Utiliser un r√©seau Docker existant

services:
  postgres:
    image: postgres:16
    container_name: qualite-postgres
    ports:
      - "5433:5432"
    networks:
      - pg-net
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: qualitedev
      POSTGRES_DB: Inventory
      TZ: Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    networks:
      - pg-net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pgdata:
